Update build-hy3000.yml

diff --git a/.github/workflows/build-hy3000.yml b/.github/workflows/build-hy3000.yml
--- a/.github/workflows/build-hy3000.yml
+++ b/.github/workflows/build-hy3000.yml
@@ -110,15 +110,16 @@ jobs:
         run: |
           cd openwrt
           ls -l
-          make defconfig
-          make -j$(nproc) V=s || echo "BUILD_FAILED=true" >> $GITHUB_ENV
+          make defconfig -j$(nproc) && make clean -j$(nproc)
+          make download -j$(nproc)
+          #   make -j$(nproc) V=s || echo "BUILD_FAILED=true" >> $GITHUB_ENV
+          make -j$(nproc) || make -j1 || make -j1 V=s
 
       # 10. 提取最后 500 行错误日志
       - name: Extract last 500 lines of build log
-        if: env.BUILD_FAILED == 'true'
         run: |
           cd openwrt
-          tail -n 500 build.log > ../last_500_lines.txt || true
+          tail -n 100 build.log > ../last_100_lines.txt || true
 
       # 11. 上传所有日志（失败时）
       - name: Upload logs
